CREATE TABLE users (
    Id SERIAL PRIMARY KEY,
    Record_Log TIMESTAMP DEFAULT NULL,
    Username varchar(255) NOT NULL,
    Email varchar(255) NOT NULL,
    Password varchar(255) NOT NULL
);

CREATE OR REPLACE FUNCTION SET_RECORD_LOG()
RETURNS TRIGGER AS $$
BEGIN
    NEW.Record_Log := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;



CREATE TRIGGER USERS_SET_RECORD_LOG
BEFORE INSERT ON users
FOR EACH ROW
EXECUTE FUNCTION SET_RECORD_LOG();

