# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  go:
    container_name: go
    build:
      context: ./go
    depends_on:
      - "postgres"
    ports:
      - 3000:3000
    env_file:
      - .env

volumes:
  dbdata: # create the volume for persisting data.
            